### ISSUE TITLE
Prefix methods are broken with case insensitive tries

### ISSUE THREAD

**Issue by rsfinn** [nathanday/ndtrie#12]
The "prefix" methods (e.g. `-everyObjectForKeyWithPrefix:`) appear not to work properly when the trie is created as case insensitive.  For example, in the test project's main.m (function `testSetOne()`) replace line 34 from:
```
    NDTrie* theTrie = [NDTrie trieWithArray:theTestTrueStrings];
```
to:
```
    NDTrie* theTrie = [[NDTrie alloc] initWithCaseInsensitive:YES array:theTestTrueStrings];
```
This should not change the behavior of the test cases (in particular, `theTestTrueStrings` contains only lowercase strings), but in fact the following assertions will fail:
- line 57 (testing `-everyObjectForKeyWithPrefix:`);
- line 60 (ditto);
- line 210 (testing `-objectEnumeratorForKeyWithPrefix:`);
- line 220 (ditto).

Inspecting the return values, it appears as though the prefix checking no longer works, and only full string matches succeed.  For example, in line 57 `theTempArray` contains @[ "cat" ] instead of @[@"cat", @"caterpillar", @"catalog"] as expected.

**Comment by rsfinn** [comment]
It looks like the change to `keyComponentForString()` that was applied in 130a55c to fix issue 6 was not applied to `keyComponentCaseInsensitiveForString()` as well. Making this change causes the case sensitive trie to pass the assertions that previously failed.

I'll fork and make a pull request when I get a chance.

**Comment by nathanday** [comment]
Thanks, I have merged you changes into my branch.
